services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - 'INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs'
    expose:
      - 8081
    networks:
      - proxy
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
networks:
  proxy:
    external: true
volumes:
  nexus-data: