services:
  agent:
    image: 1dev/agent:latest
    container_name: myagent
    restart: unless-stopped
    hostname: myagent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent/work:/agent/work
    environment:
      - serverUrl=https://onedev.site.com
      - agentToken=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
    tty: true
    healthcheck:
      test: ["CMD", "pgrep", "-f", "agent"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s