x-default-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 20s
  retries: 5
  start_period: 60s
  start_interval: 5s
x-env: &env
  restart: unless-stopped
  networks:
    - ivre-network
services:
  ivredb:
    image: mongo
    container_name: ivredb
    <<: *env
    volumes:
      - ./var_lib_mongodb:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'ok' > /dev/null 2>&1"]
      <<: *default-healthcheck
  ivreuwsgi:
    image: ivre/web-uwsgi
    container_name: ivreuwsgi
    <<: *env
    depends_on:
      - ivredb
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'ok' > /dev/null 2>&1"]
      <<: *default-healthcheck
  ivredoku:
    image: ivre/web-doku
    container_name: ivredoku
    restart: unless-stopped
    <<: *env
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'ok' > /dev/null 2>&1"]
      <<: *default-healthcheck
  ivreweb:
    image: ivre/web
    container_name: ivreweb
    restart: unless-stopped
    networks:
      - proxy
      - ivre-network
    expose:
      - 80
    depends_on:
      - ivreuwsgi
      - ivredoku
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'ok' > /dev/null 2>&1"]
      <<: *default-healthcheck
  ivreclient:
    image: ivre/client
    container_name: ivreclient
    <<: *env
    volumes:
      - ./ivre-share:/ivre-share
    depends_on:
      - ivredb
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "echo 'ok' > /dev/null 2>&1"]
      <<: *default-healthcheck
networks:
  ivre-network:
    name: ivre-network
    driver: bridge
  proxy:
    external: true