services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - 'TZ=Asia/Baku'
      - 'DIUN_WATCH_WORKERS=20'
      - 'DIUN_WATCH_SCHEDULE=* */6 * * *'
      - 'DIUN_WATCH_JITTER=30s'
      - 'DIUN_PROVIDERS_DOCKER=true'
      - 'DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true'
      - 'LOG_LEVEL=info'
      - 'LOG_JSON=false'
      - 'DIUN_NOTIF_DISCORD_WEBHOOKURL=discordurl'
      - 'DIUN_NOTIF_DISCORD_MENTIONS=@here,@everyone'
      - 'DIUN_NOTIF_DISCORD_RENDERFIELDS=true'
      - 'DIUN_NOTIF_DISCORD_TIMEOUT=30s'
      - 'DIUN_NOTIF_DISCORD_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by {{ .Meta.Hostname }} host).'
    labels:
      - "diun.enable=true"
    healthcheck:
      test: ["CMD", "echo", "health"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s