services:
  mattermost:
    image: mattermost/mattermost-team-edition:10.7.2
    container_name: mattermost
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - 'mattermost-data-config:/mattermost/config:rw'
      - 'mattermost-data-data:/mattermost/data:rw'
      - 'mattermost-data-logs:/mattermost/logs:rw'
      - 'mattermost-data-plugins:/mattermost/plugins:rw'
      - 'mattermost-data-client-plugins:/mattermost/client/plugins:rw'
      - 'mattermost-data-bleve-indexes:/mattermost/bleve-indexes:rw'
    environment:
      - 'MM_SERVICESETTINGS_SITEURL=https://chat.site.com'
      - 'TZ=Asia/Baku'
      - 'MM_SQLSETTINGS_DRIVERNAME=postgres'
      - 'MM_SQLSETTINGS_DATASOURCE=postgres://mattermost-user:changeme@postgres:5432/mattermost?sslmode=disable&connect_timeout=10'
      - 'MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes'
    expose:
      - 8065
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/mattermost/bin/mmctl", "system", "status", "--local"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
    networks:
      - mattermost-network
      - proxy
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - mattermost-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost-user
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mattermost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
    networks:
      - mattermost-network
networks:
  mattermost-network:
    name: mattermost-network
    driver: bridge
  proxy:
    external: true
volumes:
  mattermost-data-config:
  mattermost-data-data:
  mattermost-data-logs:
  mattermost-data-plugins:
  mattermost-data-client-plugins:
  mattermost-data-bleve-indexes:
  mattermost-db: