services:
  syncthing:
    image: 'linuxserver/syncthing:latest'
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=UTC'
    volumes:
      - './syncthing-config:/config'
      - './syncthing-data1:/data1'
      - './syncthing-data2:/data2'
    ports:
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    expose:
      - 8384
    networks:
      - proxy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:8384/'
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
networks:
  proxy:
    external: true
